### PR TITLE
Update Auto_Local_Threshold.java

### PR DESCRIPTION
**Pull request by landinig**
Phansalkar method: standard deviation was not computed properly

### CODE REVIEW

**Comment by ctrueden** [comment]
Wow, that's a huge bug!

@stelfrich et. al: FWIW, I double checked the Ops implementation to see whether we might have this bug in Phansalkar, but everything is fine, since we [reuse these statistical functions in a nice way](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.30.0/src/main/java/net/imagej/ops/threshold/localPhansalkar/LocalPhansalkarThreshold.java#L107).

**Comment by landinig** [comment]
Yes, a missing "t" in .sqr() vs. .sqrt()
Not trying to underestimate the bug in any way, but checked the old and new versions on some sample images and the differences were surprisingly small, probably due to the parameter value that the buggy function controls. I am very grateful that this was found too.

**Comment by ctrueden** [comment]
> checked the old and new versions on some sample images and the differences were surprisingly small

That's good to hear!

I was just struck by it, since it's a great example of a subtle but shockingly different mathematical expression.

**Comment by landinig** [comment]
@ctrueden: I do not remember if I need to do anything else about the commit I made to be delivered in the next Fiji build and delivered via the updater.

**Comment by ctrueden** [comment]
@landinig Nope, you do not need to do anything else.

I need to cut a new release, and then upload it to the update site. Doing it now.

**Comment by ctrueden** [comment]
I cut the release, and uploaded it.

**Comment by landinig** [comment]
Thank you!

**Comment by landinig** [comment]
@ctrueden  Hm... For reasons unknown I found that I did not have the Java8 update site ticked (not sure I ever did have that one on). Fiji thinks I am up to date and the update to Auto_Threshold (which is currently pointing to the Fiji update site) is not seen. Can that be?

When did the Auto_threshold move to the Java8 repo?
I suspect that this will leave users with the old version and unable to update if Java8 is not automatically selected.

**Comment by ctrueden** [comment]
Yes, users unfamiliar with [this guide](http://imagej.net/2016-05-10_-_ImageJ_HOWTO_-_Java_8,_Java_6,_Java_3D), and thus still running an old Java 6 version of Fiji, will not receive the fix. Sorry about that, but we have frozen the Fiji update site until the migration to Java 8 is fully complete.

To mitigate this, my plan is to upload a small plugin to the Fiji update site which causes ImageJ to pop up a warning that no more updates will be coming down the pipeline, unless the Java-8 update site is enabled.

Ideally I would make it also turn the update site on for you, but I do not have time to test that thoroughly right now and would not want to accidentally hose anyone's installation.

**Comment by landinig** [comment]
I understand the lack of time and so I do not want to impose any requirements, I was just trying to understand what was the situation.
About the Java8 update site: I posted today in the forum that having a java 6 install and selecting on the java8 repo and updating resulted in a non-working Fiji install, so maybe that pop up should suggest to re-download the latest Fiji and not only check the java 8 update site.

**Comment by stelfrich** [comment]
@landinig I have posted an answer in the [forum thread](http://forum.imagej.net/t/out-of-date-page-pointing-to-old-downloads/2051)

@ctrueden I'd be willing to "hose my installation" (is that really a thing?) for the sake of testing :+1:

**Pull request merged**
